### ISSUE TITLE
Backup All tables in a storage account

### ISSUE THREAD

**Issue by KapteinBabbalas** [TheByteStuff/AzureTableBackupRestore#3]
Is there a way to backup tables without specifying each individual table name?
I want to completely backup a TableStorage account with all its tables

**Comment by TheByteStuff** [comment]
Not currently.  The best that could be done would be some sort of scripting/code to iterate for you.  I can see where that would be a useful feature to have.  I'll take a look at incorporating it.  

How many tables does your environment have, do you know what the maximum row count is for your largest table and do you have a rough idea of total space taken across all tables?  I have two variants of backups one that goes direct to the Blob and the other that uses a local file.  I'm thinking that a user with a large number of tables would likely just want (need?) a direct to blob solution.  The row count question is because I am currently reviewing a problem report where the process isn't working for a table with millions of rows.

Do you envision a need to restore all tables at the same time or would selective restore/manual review of individual tables be needed?  The current processes store table backups under a directory structure for each table individually.  If a mass restore is needed, I'd probably opt for a different structure for the backup itself and would want to account for the possibility of access to an individual table/file.   

Thank you in advance for your additional input!

**Comment by KapteinBabbalas** [comment]
Thanks, I got this piece of code to get all the table names and then I loop through all off them.
I'm using the BackupTableToBlobDirect method, but I get this error on one of the bigger tables (132k entities). I have like 30 tables to backup.

TheByteStuff.AzureTableUtilities.Exceptions.BackupFailedException: Table 'SensArchive' backup failed.
 ---> Microsoft.Azure.Storage.StorageException: The uncommitted block count cannot exceed the maximum limit of 100,000 blocks.
   at Microsoft.Azure.Storage.Blob.BlobWriteStreamBase.ThrowLastExceptionIfExists()
   at Microsoft.Azure.Storage.Blob.BlobWriteStream.FlushAsync(CancellationToken token)
   at Microsoft.Azure.Storage.Blob.BlobWriteStream.Flush()
   at TheByteStuff.AzureTableUtilities.BackupAzureTables.BackupTableToBlobDirect(String TableName, String BlobRoot, Boolean Compress, Int32 RetentionDays, Int32 TimeoutSeconds, List`1 filters)

**Comment by TheByteStuff** [comment]
Someone else had reported a problem with backing up large tables using the dev package (TheByteStuff/AzureTableUtilities) which this is built on.  I just pushed a tweak to that as well as the included libraries for this tool which will hopefully address the exception you hit with the large table.  I tried it on a 60million+ entry table which was taking up about 60GB in backup space and it worked ok with the tweak.  Let me know if that helps with the 132k table.

Will look further at the "All Tables" option.  I think it will be a fairly straight forward option to loop through them and backup individually which would allow individual restore/download.  Does your use case involve the need to restore all at once?  That would require a different storage approach, sort of lumping them all together as a "backup set" of sorts.

**Comment by TheByteStuff** [comment]
I just pushed an "All" option for Backup as well as Copy.  For now a backup all will operate like you are currently doing in that the tables will backup under a different blob directory per table.  I'll think about an additional option that I'm thinking of like a "backupset" or something where the tables get backed up under a single blob directory and then can be restored together.  I'm thinking this could have some benefit for setting up test environments.

Let me know if the current change helps for your current needs as well as whether the backup is not working for the large table.
